DROP TABLE IF EXISTS CUSTOMER ;
DROP TABLE IF EXISTS JOURNEY_DETAILS;
DROP TABLE IF EXISTS ROUTE;

CREATE TABLE CUSTOMER (
  CUSTOMER_ID INT AUTO_INCREMENT  PRIMARY KEY,
  CUSTOMER_NAME VARCHAR(250) NOT NULL,
  CUSTOMER_TYPE VARCHAR(250) NOT NULL,
FAV_ROUTE VARCHAR(250) NOT NULL
);

CREATE TABLE JOURNEY_DETAILS  (
  JOURNEY_ID INT AUTO_INCREMENT  PRIMARY KEY,
  CUSTOMER_ID INT NOT NULL,
  JORNEY_FARE VARCHAR(250) NOT NULL,
ROUTE_NAME VARCHAR(250) NOT NULL,
START_DATE_TIME TIMESTAMP NOT NULL
);


CREATE TABLE ROUTE(
  ROUTE_ID INT AUTO_INCREMENT  PRIMARY KEY,
  DESTINATION VARCHAR(250) NOT NULL,
  ROUTE_NAME VARCHAR(250) NOT NULL,
  SOURCE  VARCHAR(250) NOT NULL
);

INSERT INTO CUSTOMER ( CUSTOMER_NAME, CUSTOMER_TYPE,FAV_ROUTE) VALUES
  ( 'Vikas', 'NORMAL','DELHI-PUNE'),
  ('Alex', 'VIP','DELHI-INDORE'),
   ('John', 'NORMAL','PUNE-BHOPAL'),
  ('Micky', 'PERSONNONGRETA','JAIPUR-CHENNAI');

INSERT INTO JOURNEY_DETAILS  ( CUSTOMER_ID ,JORNEY_FARE ,ROUTE_NAME,START_DATE_TIME) VALUES
  ( '1', '2.0','DELHI-PUNE','2020-11-24 00:00:01'),
 ( '2', '1.0','DELHI-INDORE','2020-11-24 00:00:01'),
( '3', '2.0','PUNE-BHOPAL','2020-11-24 00:00:01'),
 ( '1', '2.0','DELHI-PUNE','2020-11-24 00:00:01'),
( '1', '2.0','DELHI-PUNE','2020-11-25 00:00:01');


INSERT INTO ROUTE( ROUTE_ID,DESTINATION,ROUTE_NAME,SOURCE) VALUES
  ( '101', 'PUNE','DELHI-PUNE','DELHI'),
  ( '102', 'INDORE','DELHI-INDORE','DELHI'),
  ( '103', 'BHOPAL','PUNE-BHOPAL','PUNE'),
   ( '104', 'CHENNAI','JAIPUR-CHENNAI','JAIPUR');



